# ===========================
# APPLICATION
# ===========================
spring.application.name=semesterx-backend

# ===========================
# SERVER
# ===========================
server.port=${PORT:8081}

# ===========================
# MYSQL DATABASE
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3307/semesterx
spring.datasource.username=root
spring.datasource.password=trishnika@30
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ===========================
# GOOGLE AUTH
# ===========================
google.client.id=${GOOGLE_CLIENT_ID:test}


# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
app.upload-dir=uploads
# ===========================
# GOOGLE AUTH
# ===========================
google.client.id=${GOOGLE_CLIENT_ID}

# ===========================
# JWT
# ===========================
jwt.secret=SemesterXSuperSecureJwtSecretKeyForDevelopmentOnlyChangeThisBeforeProduction123456
jwt.expiration=86400000